version: '3'
services:
    mysql-service:
        environment:
            - MYSQL_ROOT_PASSWORD=Devops@123
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpress_user
            - MYSQL_PASSWORD=Wordpress@123
        container_name: wordpress_db_container
        image: mysql:8.0.32
    wordpress-service:
        ports:
            - '80:80'
        image: nischal9860/word_press_image:latest 
        container_name: wordpress_app_container
        
